name: Binary Creation Action

on:
  workflow_dispatch: 

jobs:
  build:
    name: Build and Upload Binary
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
    steps:

      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install uv
        uses: astral-sh/setup-uv@v5

      - name: Install the project
        run: uv sync --locked --all-extras --dev


      - name: Build executable
        run: pyinstaller --clen metavision.spec
    
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: metavision-${{matrix.os}}
          path: dist/